// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psgodukfouzoqbvyolzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzZ29kdWtmb3V6b3FidnlvbHpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzk1NjIsImV4cCI6MjA2NTY1NTU2Mn0.tRTUVpz3AnBoV1LgGdcuzd-DS9wuaGb-G-pH65CK1CM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);